### ISSUE TITLE
how to connect with websockets?

### ISSUE THREAD

**Issue by VIRAL69** [nats-io/nats.py#353] opened 2022-09-17 16:34 UTC
is there a way to connect with websockets?

it is possible to write my own code to connect to the nats? What I should consider?
Is there a way this libary will support nats.ws?

**Comment by wallyqs** [comment] 2022-09-17 17:44
need to reimplement the transport for websockets, first step would be to pick a websocket dependency for nats.py

**Comment by bvanelli** [comment] 2022-09-18 09:02
I think this is a duplicate of https://github.com/nats-io/nats.py/issues/270

For dependency, I can recommend [websockets](https://websockets.readthedocs.io/en/stable/), as I have been using it quite a while without any issues. 

I have interest into developing this feature. Currently nats.py uses (self._io_reader, self._io_writer) for the transport, I was wondering how to integrate websockets, if the current api would be enough or if we have to develop something different (like a subclass for transports insteads). In theory, the transport with websockets looks exactly the same as with tcp connections.

I have implemented the transport already, it's just a matter of integration. @wallyqs do you have any input on what's the best way of doing it?

**Comment by VIRAL69** [comment] 2022-09-18 10:08
@bvanelli would be very nice if you could contribute the websockets support.
I already tried with a basic websocket connection with the same libary but I failed miserable. Because there is an authentication needed, I am able to connect to the websocket and receive messages but I just fail to authenticate myself, seems like the message I am sending isn't received correctly...

**Comment by bvanelli** [comment] 2022-09-18 11:46
I created a branch with my first draft [here](https://github.com/nats-io/nats.py/compare/main...bvanelli:nats.py:feature/implement-websockets?expand=1), I'll try to get it working perhaps today.

The api for websocket and tcp connection is quite similar so it may no be that much of a hassle after all.

**Comment by VIRAL69** [comment] 2022-09-18 13:37
Sounds very good, would be very kind from you. 🙏

**Comment by wallyqs** [comment] 2022-09-18 14:41
@bvanelli I had a quick look and it looks really promising! There is a public demo endpoint with websocket support here that has TLS enabled to avoid setting up a server: `wss://demo.nats.io:8443`

**Comment by bvanelli** [comment] 2022-09-18 17:55
I managed to get nats working with websocket for a simple example:

/tmp/nats.conf
```
port: 4222

websocket
{
    port: 8080
    no_tls: true
}
```

I then run a nats server locally:

```
docker run -it --rm -d --name nats -v /tmp/:/container/ -p 8080:8080 -p 4222:4222 nats -c /container/nats.conf
```

And a script for testing:

```python
import asyncio
import nats


async def main():
    nc = await nats.connect("ws://localhost:8080")

    async def message_handler(msg):
        subject = msg.subject
        reply = msg.reply
        data = msg.data.decode()
        print("Received a message on '{subject} {reply}': {data}".format(
            subject=subject, reply=reply, data=data))

    # Simple publisher and async subscriber via coroutine.
    sub = await nc.subscribe("foo", cb=message_handler)

    await nc.publish("foo", b'Hello')
    await nc.publish("foo", b'World')
    await nc.publish("foo", b'!!!!!')

    await asyncio.sleep(5)

    await sub.unsubscribe()

    # Terminate connection to NATS.
    await nc.close()


if __name__ == '__main__':
    asyncio.run(main())
```

I get as result:

```
Received a message on 'foo ': Hello
Received a message on 'foo ': World
Received a message on 'foo ': !!!!!
```

Still having problem terminating the stream with drain. The ping doesn't get any reply for some reason, maybe I'm missing something. Authentication also work, although I have only tested token authentication. TLS still needs to be implemented.

I had to switch to `aiohttp` for the underlying websocket implementation because `websockets` was a bit of a pain to integrate, as I get some weird exceptions. aiohttp, however, did fine. Probably needs more testing but for prototyping is fine.

**Comment by VIRAL69** [comment] 2022-09-20 07:50
sounds very promising, thanks for the effort!

**Comment by bvanelli** [comment] 2022-09-20 17:14
I finished mostly the implementation, so I'll open a draft PR here https://github.com/nats-io/nats.py/pull/356 to document open points.

**Comment by VIRAL69** [comment] 2022-09-20 19:13
thank you so much 🙏
hopefully it will be merged soon :)

**Closed** 2022-09-25 00:05 UTC
